mode: auto
silent: false
branchName: '${issue.number}'
branches:
  - label: type:feature
    prefix: feat-
  - label: type:bug
    prefix: bug-
  - label: type:epic
    prefix: epic-
  - label: type:docs
    prefix: docs-
  - label: type:automation
    prefix: auto-
autoCloseIssue: true
