stages:
- build

build:
  stage: build
  only:
  - tags
  image: docker:19.03.15
  services:
  - docker:19.03.15-dind
  variables:
    IMAGE_TAG: "$CI_REGISTRY_IMAGE:$CI_COMMIT_TAG"
  script:
  - docker login -u $CI_REGISTRY_USER -p $CI_REGISTRY_PASSWORD $CI_REGISTRY
  - docker build -t $CI_REGISTRY_IMAGE:latest -t $IMAGE_TAG .
  - docker build -t $IMAGE_TAG -t $CI_REGISTRY_IMAGE:latest .
  - docker push $IMAGE_TAG
  - docker push $CI_REGISTRY_IMAGE:latest
