name: Stale issues and PRs

on:
  schedule:
    - cron: "0 0 * * *"

jobs:
  stale:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/stale@v8
        with:
          repo-token: ${{ secrets.GITHUB_TOKEN }}
          stale-issue-message: "This issue has been marked as stale due to inactivity. If this issue is still ongoing, please leave a comment."
          stale-pr-message: "This pull request has been marked as stale due to inactivity. If this issue is still ongoing, please leave a comment."
          stale-issue-label: "status:stale"
          stale-pr-label: "status:stale"
